### ISSUE TITLE
Upload to PyPi

### ISSUE THREAD

**Issue by tfeldmann** [rigglemania/pysqlcipher3#1]

**Comment by rigglemania** [comment]
The package is now uploaded: https://pypi.python.org/pypi/pysqlcipher3. I'm not terribly familiar with Python packaging as this is my first package uploaded to PyPi, so let me know if you run into any issues. A good way to verify things are working is to make sure all the unit tests pass after installing pysqlcipher3. 

    from pysqlcipher3 import test
    test.test()

**Comment by tfeldmann** [comment]
I'm on Mac OS X 10.10.2 and didn't have lsqlcipher installed, so I needed to run

    brew install sqlcipher

before installation. Now everything works fine and the tests pass. I will try to port some small applications using pysqlcipher to using pysqlcipher3. I'll let you know if I find any issues :+1:

**Comment by rigglemania** [comment]
That sounds right. The default installation is to link against the sqlcipher libary installed on your machine. I've looked at the Python documentation and I don't see a way to specify the non-Python dependency in the setup config, so I'll at least include in the README and make sure it's mentioned somewhere on PyPi.

**Comment by rigglemania** [comment]
I'm going to close this. Create a new issue if you find any issues.
