### ISSUE TITLE
Problem on building for Windows

### ISSUE THREAD

**Issue by masoudr** [rigglemania/pysqlcipher3#10]
Hi,
I'm trying to build Pysqlcipher on Windows X64 and Python X64 3.6.
I just found a prebuilt version of `sqlcipher.lib` file in [here](https://github.com/couchbaselabs/couchbase-lite-libsqlcipher). I put the `sqlsipher.lib` file next to `setup.py` file. Then I downloaded the source of `sqlite3` files and put the `.c` files in `src` folder.  When I run `python setup.py install` I get the following error:
```
LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol RAND_bytes
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol RAND_add
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol OBJ_nid2sn
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_MD_size
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_CIPHER_nid
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_CIPHER_block_size
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_CIPHER_key_length
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_CIPHER_iv_length
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_CipherInit
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_CipherUpdate
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_CipherFinal
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_CIPHER_CTX_cleanup
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_CIPHER_CTX_set_padding
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_sha1
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol OPENSSL_add_all_algorithms_noconf
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_get_cipherbyname
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol EVP_cleanup
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol PKCS5_PBKDF2_HMAC_SHA1
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol HMAC_CTX_init
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol HMAC_CTX_cleanup
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol HMAC_Init_ex
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol HMAC_Update
sqlcipher.lib(sqlite3.obj) : error LNK2001: unresolved external symbol HMAC_Final
build\lib.win-amd64-3.6\pysqlcipher3\_sqlite3.cp36-win_amd64.pyd : fatal error LNK1120: 23 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120
```
I am not sure if this is the problem for sqlcipher.lib or not. Do I need to link `openssl` library too?
I also find the similar problem to [here](https://github.com/leapcode/pysqlcipher/issues/23) but I can't figure it out how to solve it.
Thanks.

**Comment by rigglemania** [comment]
I don't really know anything about this prebuilt library, but maybe it was built with different options that are incompatible with the build on your local machine. I don't have a working Windows environment, so I can't really test, but if you find a solution that requires code changes, I'm happy to accept pull requests.

**Comment by masoudr** [comment]
@rigglemania Actually building procedure of the `sqlcipher` on windows are not clear and I couldn't find a well-documented source for that even on its repo. I'm not sure about my problem cause. I think it is all related to `sqlcipher`. Anyway, if I found a workaround I will post it here. Thanks.

**Comment by masoudr** [comment]
@Xuepaopao It seems that it is a common problem that related to `sqlcipher` on windows itself. it is not the problem of `pysqlcipher`. It seems that building on windows is too complicated and they sell it as a product.

**Comment by Xuepaopao** [comment]
@masoudr okay Thank you for answering my question
