### ISSUE TITLE
Did the project dissapear from pypi?

### ISSUE THREAD

**Issue by LefterisJP** [rigglemania/pysqlcipher3#14]
Hello!

We have been using your port of pysqlcipher for python 3 for quite some time now in https://github.com/rotkehlchenio/rotkehlchen/.

Just today I noticed that our tests failed [here](https://travis-ci.org/rotkehlchenio/rotkehlchen/jobs/436875465#L699), complaining that pip can't find `pysqlcipher3`.

And sure enough the project seems to no longer be on pypi: https://pypi.org/search/?q=pysqlcipher3

What happened? Did you somehow remove it? If so why? Is there a viable alternative for python 3?

**Comment by LefterisJP** [comment]
@rigglemania I just saw [this](https://github.com/rigglemania/pysqlcipher3/issues/12) issue where you explain why you removed it.

The package works fine for me at least until now, both in Linux and OSX.

I would appreciate if it you put it back up in pypi. If people have problems we can all help them, and if you don't have the time to do so that's perfectly fine. Nobody expects you to. It's open source :)

If you don't put it back in pypi I will fork it and put it myself as our project really needs pysqlcipher for python 3. Hope you can understant.

**Comment by rigglemania** [comment]
Sorry about that. I don't have time to manage this project, including responding to all these issues. I'll add a notice on the repo page. It should be back now, although I was forced to bump the version to 1.0.3

**Comment by LefterisJP** [comment]
@rigglemania Thank you. I understand. The best scenario is for this to get more love and get merged back to the upstream.
