### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by ozanh** [rigglemania/pysqlcipher3#4]
Hi,
I having trouble with a test method `testAddPassword` which is in `sqlcipher.py`.
Are you able to run the tests without any exceptions and failures?

**Comment by rigglemania** [comment]
I haven't tried running any tests lately, but considering nothing has changed in this repo for a while, any failures would have to be caused by external dependency changes like the sqlcipher lib or version of python you are using.

**Comment by ozanh** [comment]
I built it under win7 with mingw32 compiler. Have you ever tested it under any windows? os.rename function raises exception in testAddPassword as far as I remember. Other tests are OK.

**Comment by rigglemania** [comment]
I built in once on Windows, but I think I used the Visual Studio compiler. What's the exact exception you are seeing. If it's with os.rename, that sounds like a Python issue (maybe with permissions of files/folders on your system)

**Comment by ozanh** [comment]
Hi,
![sqlcipher3_test_error](https://cloud.githubusercontent.com/assets/16383613/17763832/f1517ac2-6523-11e6-9025-02b7a357ceb6.PNG)
You can see the exception above.
Actually, the problem is due to `os.rename` behaves differently under windows and Linux.
In windows, `os.rename(old, new)` raises exception if new file name is already in the system but Linux just replaces the new file if it exists. It works like `mv` command in linux.
Moreover, `rename` function in `C Programming`  in Linux works as same as python's `os.rename` in Linux as far as I have tested.
Using a nonexistent new file name would solve the problem.

**Comment by rigglemania** [comment]
Based on your screenshot, are you running python2 rather than python3? I wonder if the behavior changed between releases. So it sounds like a rename in Windows would to do a file copy and then delete the old file. I primarily run Linux, so if you find a fix on Windows, I'm more than open to accepting PRs.

**Comment by ozanh** [comment]
I have created a pull request. I run the tests with Python 2.7 and 3.4 on windows OS with success. I have also created wheels using mingw32 compiler, they all work good if `libeay32.dll` is accessible. Thanks.
