### ISSUE TITLE
Build Python x64

### ISSUE THREAD

**Issue by lompal** [rigglemania/pysqlcipher3#9]
> Install the latest version of Python 3 (32-bit): if you have Python 64-bit installed, you may have to uninstall it before installing Python 32-bit.

Hello, is it possible to build with Python x64?
Thanks!

**Comment by lompal** [comment]
I found the way:
- Make sure that you are using OpenSSL-Win64
- Set the PATH to Win64 environment
- Copy the OpenSSL folder
- Build the amalgamation and install with the latest Python x64
Instruction is almost same, just make sure that all dependencies are x64

**Comment by rigglemania** [comment]
Thanks for the following up. I've added the 64 bit instructions to the README.
